language: python
env:
- TOXENV=py27
- TOXENV=py27-flake8
- TOXENV=py3
- TOXENV=py3-flake8
install: pip install tox
script: tox
before_install:
  - sudo apt-get update
  - sudo apt-get install -y python-tk python3-tk
